const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@ Martin Orellana";
const email = "Name";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*****";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Martin Orellana";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const createNewAccount = "or, create new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account?";

